default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'shopone_dev' %>

test:
  <<: *default
  database: shopone_test

production:
  <<: *default
  database: shopone_production
  username: shopone
  password: <%= ENV['SHOPONE_DATABASE_PASSWORD'] %>
